[[main]]
	identifier = 'About'
	name = 'About'
	weight = 1
[[main]]
	parent = 'About'
	name = 'me'
	url = '/me/'
	weight = 1
	[main.params]
		class = ''
[[main]]
	parent = 'About'
	name = 'TodayILearned'
	url = '/TodayILearned/'
	weight = 2
	[main.params]
		class = ''
[[main]]
	identifier = 'Posts'
	name = 'Posts'
	weight = 2
[[main]]
	parent = 'Posts'
	name = 'math'
	url = '/math/'
	weight = 1
	[main.params]
		class = ''
[[main]]
	parent = 'Posts'
	name = 'project'
	url = '/project/'
	weight = 2
	[main.params]
		class = ''
