# collections:
#   authors:
#     output: #true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Information of blogger
blogger:
  name: "Jae Choi" # for profile
  penname: "Jae Choi" # for each post
  comment: # "Hello" # for profile

  profile: false

  github: https://github.com/chillinjae/ # github url
  site: https://blog.jaechoi.dev # personal site url
  email: mailto:blog@jaechoi.dev # email address



# permalink
permalink: /:categories/:year:month:day/:title/

# time zone
timezone: Canada/Pacific

# Markdown
markdown: kramdown
kramdown:
  imput: GFM
  syntax_highlighter: rouge
  math_engine: katex
  math_engine_opts: {}

# Disqus
discus-identifier: chillinjae

# Plug-ins
# plugins: 
#   - jekyll-latex

# Pagination
# plugins:
#   - jekyll-paginate-v2
# pagination:
#   enabled: true
#   per_page: 6
#   sort_reverse: true


